import type {
  EnvFieldDefinition,
  EnvFieldGroup,
} from "./env-types.js";

export const envFieldDefinitions: EnvFieldDefinition[] = [
  field("DEFAULT_REALTIME_PROVIDER", "voice", "Realtime provider", "Default voice runtime.", ["gemini", "openai"], "gemini"),
  field("VOICE_SERVER_HOST", "voice", "Server host", "Bun starter server bind host. Keep 127.0.0.1 for local dev.", undefined, "127.0.0.1"),
  field("VOICE_PUBLIC_HOST", "voice", "Public host", "Host announced to the browser in /config.", undefined, "127.0.0.1"),
  field("VITE_DEV_HOST", "voice", "Vite host", "Vite dev server bind host.", undefined, "127.0.0.1"),
  field("GEMINI_API_KEY", "voice", "Gemini API key", "Enables Gemini Live voice and Gemini planner.", undefined, undefined, true),
  field("GOOGLE_API_KEY", "voice", "Google API key", "Alternative Gemini key name supported by the starter.", undefined, undefined, true),
  field("GEMINI_REALTIME_MODEL", "voice", "Gemini voice model", "Gemini Live model used by the RTC lab.", undefined, "gemini-3.1-flash-live-preview"),
  field("GEMINI_REALTIME_VOICE", "voice", "Gemini voice", "Voice name used by Gemini Live.", undefined, "Puck"),
  field("OPENAI_API_KEY", "voice", "OpenAI API key", "Enables OpenAI Realtime voice.", undefined, undefined, true),
  field("OPENAI_REALTIME_MODEL", "voice", "OpenAI realtime model", "OpenAI Realtime model used by the RTC lab.", undefined, "gpt-realtime-1.5"),
  field("OPENAI_REALTIME_VOICE", "voice", "OpenAI voice", "Voice name used by OpenAI Realtime.", undefined, "marin"),
  field("BUILDER_PROMPT_PROVIDER", "builder", "Planner provider", "Adaptive planner provider for prompt/build tasks.", ["gemini", "deepseek", "qwen", "kimi"], "gemini"),
  field("GEMINI_TEXT_MODEL", "builder", "Gemini text model", "Gemini model for builder planning tasks.", undefined, "gemini-3.5-flash"),
  field("DEEPSEEK_API_KEY", "builder", "DeepSeek API key", "Enables DeepSeek planner/research profiles.", undefined, undefined, true),
  field("DEEPSEEK_MODEL", "builder", "DeepSeek model", "DeepSeek model for builder planning tasks.", undefined, "deepseek-v4-pro"),
  field("QWEN_API_KEY", "builder", "Qwen API key", "Enables Qwen planner/research profiles.", undefined, undefined, true),
  field("DASHSCOPE_API_KEY", "builder", "DashScope API key", "Alternative Qwen key name supported by the starter.", undefined, undefined, true),
  field("QWEN_MODEL", "builder", "Qwen model", "Qwen model for builder planning tasks.", undefined, "qwen-plus"),
  field("KIMI_API_KEY", "builder", "Kimi API key", "Enables Kimi verifier/research profiles.", undefined, undefined, true),
  field("MOONSHOT_API_KEY", "builder", "Moonshot API key", "Alternative Kimi key name supported by the starter.", undefined, undefined, true),
  field("KIMI_MODEL", "builder", "Kimi model", "Kimi model for verification tasks.", undefined, "kimi-k2.6"),
  field("BUILDER_DOCUMENT_PARSE_TIMEOUT_MS", "builder", "Document parse timeout", "Max parser time before ingestion fails closed.", undefined, "5000"),
  field("BUILDER_DOCUMENT_INGESTION_QUOTA_PER_IP", "builder", "Document quota", "Max document ingestions per IP in the quota window.", undefined, "20"),
  field("BUILDER_DOCUMENT_INGESTION_QUOTA_WINDOW_MS", "builder", "Document quota window", "Rolling quota window for document ingestion.", undefined, "60000"),
  field("VOYAGE_API_KEY", "knowledge", "Voyage API key", "Enables embeddings for RAG/knowledge search.", undefined, undefined, true),
  field("DATABASE_URL", "knowledge", "Postgres URL", "Postgres/pgvector source of truth.", undefined, undefined, true),
  field("BUILDER_INFRA_APPLY_DRIVER", "infra", "Apply driver", "Dev-local plans by default; external, K3s, and kubectl are opt-in.", ["dev-local", "external", "k3s-docker", "kubectl"], "dev-local"),
  field("BUILDER_INFRA_COMPUTE_TARGET", "infra", "Compute target", "IaC compute target emitted by the planner.", ["local", "k3s", "kubernetes", "managed", "vm"], "local"),
  field("BUILDER_INFRA_TOFU_MODULE_DIR", "infra", "OpenTofu module dir", "Required for the external infra runner.", undefined, undefined, false),
  field("BUILDER_INFRA_K3S_PORT", "infra", "K3s API port", "Local K3s API port exposed through Docker.", undefined, "16443"),
  field("BUILDER_VECTOR_BACKEND", "infra", "Vector backend", "Optional vector backend override.", ["postgres-pgvector", "milvus"], "postgres-pgvector"),
  field("MILVUS_URL", "infra", "Milvus URL", "Optional Milvus endpoint for vector-heavy agents.", undefined, undefined, true),
  field("NEO4J_URI", "infra", "Graph URI", "Optional graph endpoint for graph-ready agents.", undefined, undefined, true),
  field("GRAPH_DATABASE_URL", "infra", "Graph database URL", "Optional Neo4j/Memgraph compatible graph endpoint.", undefined, undefined, true),
  field("MEMGRAPH_URI", "infra", "Memgraph URI", "Optional Memgraph endpoint for graph-ready agents.", undefined, undefined, true),
  field("AGENT_LEARNING_GRAPH_DRIVER", "infra", "Learning graph driver", "Use local, Postgres, Neo4j, or Memgraph graph memory.", ["local", "postgres", "neo4j", "memgraph"], "local"),
  field("AGENT_LEARNING_ENABLED", "infra", "Session learning", "Enables post-session memory and agent version evolution.", ["true", "false"], "true"),
  field("AGENT_LEARNING_PROFILE", "infra", "Learning profile", "Controls post-session learning mutation behavior.", ["observe", "memory_only", "memory_and_candidates", "auto_apply_prompt_safe", "approval_required"], "auto_apply_prompt_safe"),
  field("AGENT_LEARNING_WORKFLOW_DRIVER", "infra", "Learning workflow driver", "Use local in-process learning in dev or dispatch to a Temporal worker.", ["local", "temporal"], "local"),
  field("AGENT_LEARNING_MEMORY_DRIVER", "infra", "Learning memory driver", "Use local in-memory learning in dev or Redis temporal memory.", ["local", "redis"], "local"),
  field("AGENT_LEARNING_MEMORY_NAMESPACE", "infra", "Learning memory namespace", "Redis key namespace for temporal learned memory.", undefined, "agent-learning"),
  field("REDIS_URL", "infra", "Redis URL", "Redis temporal memory for learned session facts and user preferences.", undefined, undefined, true),
  field("TEMPORAL_ADDRESS", "infra", "Temporal address", "Temporal workflow endpoint for post-session learning jobs.", undefined, "localhost:7233"),
  field("TEMPORAL_NAMESPACE", "infra", "Temporal namespace", "Temporal namespace used by the learning worker.", undefined, "default"),
  field("TEMPORAL_TASK_QUEUE", "infra", "Temporal task queue", "Task queue consumed by the learning worker.", undefined, "agent-learning"),
  field("TEMPORAL_WORKFLOW_TYPE", "infra", "Temporal workflow type", "Workflow type started for post-session learning.", undefined, "learnFromSession"),
  field("AGENT_LEARNING_MEMORY_TTL_SECONDS", "infra", "Learning TTL", "Redis TTL for temporal learned memory.", undefined, "2592000"),
  field("VOICE_DEV_AUTH_TOKEN", "auth", "Server auth token", "Protects builder and voice websocket routes when set.", undefined, undefined, true),
  field("VITE_VOICE_DEV_AUTH_TOKEN", "auth", "Client auth token", "Browser-side token mirrored for local dev.", undefined, undefined, true),
  field("VOICE_ALLOWED_ORIGINS", "auth", "Allowed origins", "Comma-separated CORS origins for the starter server.", undefined, "http://localhost:5177,http://127.0.0.1:5177"),
];

function field(
  name: string,
  group: EnvFieldGroup,
  label: string,
  description: string,
  options?: string[],
  defaultValue?: string,
  secret = false,
): EnvFieldDefinition {
  return { name, group, label, description, options, defaultValue, secret, restartRequired: true };
}
