import type { SessionState } from "../../types/index.js";

export const STATE_TRANSITIONS: Record<SessionState, SessionState[]> = {
  initializing: ["connecting", "error"],
  connecting: ["authenticating", "active", "error"],
  authenticating: ["awaiting_pin", "active", "error", "auth_failed"],
  awaiting_pin: ["verifying_pin", "error", "auth_failed"],
  verifying_pin: ["active", "awaiting_pin", "error", "auth_failed"],
  active: [
    "listening",
    "speaking",
    "processing",
    "interrupted",
    "paused",
    "quota_warning",
    "ending",
    "error",
  ],
  listening: [
    "speaking",
    "processing",
    "interrupted",
    "active",
    "ending",
    "error",
  ],
  speaking: [
    "listening",
    "processing",
    "interrupted",
    "active",
    "ending",
    "error",
  ],
  processing: ["processing_tool", "speaking", "active", "error"],
  processing_tool: ["speaking", "active", "processing", "error"],
  interrupted: ["listening", "active", "ending", "error"],
  paused: ["active", "ending", "error"],
  quota_warning: ["active", "listening", "speaking", "ending", "error"],
  ending: ["ended", "error"],
  ended: [],
  error: ["ending", "fatal_error"],
  fatal_error: [],
  auth_failed: [],
};
